% Average Bond Lifetime Figure Script

load('Avg_BL_data.mat');
Color_array = [ 0 1 0; 0 0.749 1; 0 0 1; 0.502 0 1; 1 0 0 ];

XTick_vec_slip  = [1 2 3 4 6 7 8 10 11 12];
XTick_vec_catch = [1 2 3 4 6 7 8 9 11 12 13 14];
XTick_vec_tot   = [1 2 3 4 5 7 8 9 10 12 13 14 15];

xtick_label_slip    = {'$0 \%$','$10 \%$','$20 \%$','$30 \%$','$10 \%$','$20 \%$',...
    '$30 \%$','$10 \%$','$20 \%$','$30 \%$'};
xtick_label_catch   = {'$10 \%$','$20 \%$','$30 \%$','$100 \%$','$10 \%$',...
    '$20 \%$','$30 \%$','$100 \%$','$10 \%$','$20 \%$','$30 \%$','$100 \%$'};
xtick_label_tot     = {'$0 \%$','$10 \%$','$20 \%$','$30 \%$','$100 \%$','$10 \%$',...
    '$20 \%$','$30 \%$','$100 \%$','$10 \%$','$20 \%$','$30 \%$','$100 \%$'};

figure(1); hold on; set(gcf,'Color','w'); 
set(gca,'TickLabelInterpreter','LaTeX','XTick',XTick_vec_slip,'XTickLabel',...
    xtick_label_slip,'LineWidth',2.5,'FontSize',75); xtickangle(45); 
ylabel('$\langle \tau_{\mathrm{slip}} \rangle$ ($\mathrm{s}$)','Interpreter',...
    'LaTeX','FontSize',90);
plot(1,E1_1x_Bond_Lifetime(1),'gs','MarkerSize',26,'LineWidth',4,...
    'MarkerFaceColor','w');
plot(2,SSB_0_1_Bond_Lifetime(1),'s','MarkerSize',26,'LineWidth',4,...
    'MarkerFaceColor','w','MarkerEdgeColor',Color_array(2,:));
plot(3,SSB_0_2_Bond_Lifetime(1),'bs','MarkerSize',26,'LineWidth',4,...
    'MarkerFaceColor','w');
plot(4,SSB_0_3_Bond_Lifetime(1),'s','MarkerSize',26,'LineWidth',4,...
    'MarkerFaceColor','w','MarkerEdgeColor',Color_array(4,:));

plot(6,OVA_0_1_Bond_Lifetime(1),'s','MarkerSize',26,'LineWidth',4,...
    'MarkerFaceColor','w','MarkerEdgeColor',Color_array(2,:));
plot(7,OVA_0_2_Bond_Lifetime(1),'bs','MarkerSize',26,'LineWidth',4,...
    'MarkerFaceColor','w');
plot(8,OVA_0_3_Bond_Lifetime(1),'s','MarkerSize',26,'LineWidth',4,...
    'MarkerFaceColor','w','MarkerEdgeColor',Color_array(4,:));

plot(10,VSV8_0_1_Bond_Lifetime(1),'s','MarkerSize',26,'LineWidth',4,...
    'MarkerFaceColor','w','MarkerEdgeColor',Color_array(2,:));
plot(11,VSV8_0_2_Bond_Lifetime(1),'bs','MarkerSize',26,'LineWidth',4,...
    'MarkerFaceColor','w');
plot(12,VSV8_0_3_Bond_Lifetime(1),'s','MarkerSize',26,'LineWidth',4,...
    'MarkerFaceColor','w','MarkerEdgeColor',Color_array(4,:));
box on; axis([0 13 0 0.20]); hold off;

figure(2); hold on; set(gcf,'Color','w'); 
set(gca,'TickLabelInterpreter','LaTeX','XTick',XTick_vec_catch,'XTickLabel',...
    xtick_label_catch,'LineWidth',2.5,'FontSize',75); xtickangle(45); 
ylabel('$\langle \tau_{\mathrm{catch}} \rangle$ ($\mathrm{s}$)','Interpreter',...
    'LaTeX','FontSize',90);
plot(1,SSB_0_1_Bond_Lifetime(3),'d','MarkerSize',26,'LineWidth',4,...
    'MarkerFaceColor',Color_array(2,:),'MarkerEdgeColor',Color_array(2,:));
plot(2,SSB_0_2_Bond_Lifetime(3),'d','MarkerSize',26,'LineWidth',4,...
    'MarkerFaceColor','b','MarkerEdgeColor','b');
plot(3,SSB_0_3_Bond_Lifetime(3),'d','MarkerSize',26,'LineWidth',4,...
    'MarkerFaceColor',Color_array(4,:),'MarkerEdgeColor',Color_array(4,:));
plot(4,SSB_1x_Bond_Lifetime(3),'d','MarkerSize',26,'LineWidth',4,...
    'MarkerFaceColor','r','MarkerEdgeColor','r');

plot(6,OVA_0_1_Bond_Lifetime(3),'d','MarkerSize',26,'LineWidth',4,...
    'MarkerFaceColor',Color_array(2,:),'MarkerEdgeColor',Color_array(2,:));
plot(7,OVA_0_2_Bond_Lifetime(3),'d','MarkerSize',26,'LineWidth',4,...
    'MarkerFaceColor','b','MarkerEdgeColor','b');
plot(8,OVA_0_3_Bond_Lifetime(3),'d','MarkerSize',26,'LineWidth',4,...
    'MarkerFaceColor',Color_array(4,:),'MarkerEdgeColor',Color_array(4,:));
plot(9,OVA_1x_Bond_Lifetime(3),'d','MarkerSize',26,'LineWidth',4,...
    'MarkerFaceColor','r','MarkerEdgeColor','r');

plot(11,VSV8_0_1_Bond_Lifetime(3),'d','MarkerSize',26,'LineWidth',4,...
    'MarkerFaceColor',Color_array(2,:),'MarkerEdgeColor',Color_array(2,:));
plot(12,VSV8_0_2_Bond_Lifetime(3),'d','MarkerSize',26,'LineWidth',4,...
    'MarkerFaceColor','b','MarkerEdgeColor','b');
plot(13,VSV8_0_3_Bond_Lifetime(3),'d','MarkerSize',26,'LineWidth',4,...
    'MarkerFaceColor',Color_array(4,:),'MarkerEdgeColor',Color_array(4,:));
plot(14,VSV8_1x_Bond_Lifetime(3),'d','MarkerSize',26,'LineWidth',4,...
    'MarkerFaceColor','r','MarkerEdgeColor','r');
box on; axis([0 15 0 0.80]); hold off;

figure(3); hold on; set(gcf,'Color','w'); 
set(gca,'TickLabelInterpreter','LaTeX','XTick',XTick_vec_tot,'XTickLabel',...
    xtick_label_tot,'LineWidth',2.5,'FontSize',60); xtickangle(45); 
ylabel('$\langle \tau \rangle$ ($\mathrm{s}$)','Interpreter','LaTeX','FontSize',90);
plot(-10,0,'ks','MarkerSize',26,'LineWidth',4,'MarkerFaceColor','w');
plot(-10,0,'kd','MarkerSize',26,'LineWidth',4,'MarkerFaceColor','k');

plot(1,E1_1x_Bond_Lifetime(1),'gs','MarkerSize',26,'LineWidth',4,...
    'MarkerFaceColor','w');
plot(2,SSB_0_1_Bond_Lifetime(1),'s','MarkerSize',26,'LineWidth',4,...
    'MarkerFaceColor','w','MarkerEdgeColor',Color_array(2,:));
plot(2,SSB_0_1_Bond_Lifetime(3),'d','MarkerSize',26,'LineWidth',4,...
    'MarkerFaceColor',Color_array(2,:),'MarkerEdgeColor',Color_array(2,:));
plot(3,SSB_0_2_Bond_Lifetime(1),'bs','MarkerSize',26,'LineWidth',4,...
    'MarkerFaceColor','w');
plot(3,SSB_0_2_Bond_Lifetime(3),'d','MarkerSize',26,'LineWidth',4,...
    'MarkerFaceColor','b','MarkerEdgeColor','b');
plot(4,SSB_0_3_Bond_Lifetime(1),'s','MarkerSize',26,'LineWidth',4,...
    'MarkerFaceColor','w','MarkerEdgeColor',Color_array(4,:));
plot(4,SSB_0_3_Bond_Lifetime(3),'d','MarkerSize',26,'LineWidth',4,...
    'MarkerFaceColor',Color_array(4,:),'MarkerEdgeColor',Color_array(4,:));
plot(5,SSB_1x_Bond_Lifetime(3),'d','MarkerSize',26,'LineWidth',4,...
    'MarkerFaceColor','r','MarkerEdgeColor','r');

plot(7,OVA_0_1_Bond_Lifetime(1),'s','MarkerSize',26,'LineWidth',4,...
    'MarkerFaceColor','w','MarkerEdgeColor',Color_array(2,:));
plot(7,OVA_0_1_Bond_Lifetime(3),'d','MarkerSize',26,'LineWidth',4,...
    'MarkerFaceColor',Color_array(2,:),'MarkerEdgeColor',Color_array(2,:));
plot(8,OVA_0_2_Bond_Lifetime(1),'bs','MarkerSize',26,'LineWidth',4,...
    'MarkerFaceColor','w');
plot(8,OVA_0_2_Bond_Lifetime(3),'d','MarkerSize',26,'LineWidth',4,...
    'MarkerFaceColor','b','MarkerEdgeColor','b');
plot(9,OVA_0_3_Bond_Lifetime(1),'s','MarkerSize',26,'LineWidth',4,...
    'MarkerFaceColor','w','MarkerEdgeColor',Color_array(4,:));
plot(9,OVA_0_3_Bond_Lifetime(3),'d','MarkerSize',26,'LineWidth',4,...
    'MarkerFaceColor',Color_array(4,:),'MarkerEdgeColor',Color_array(4,:));
plot(10,OVA_1x_Bond_Lifetime(3),'d','MarkerSize',26,'LineWidth',4,...
    'MarkerFaceColor','r','MarkerEdgeColor','r');

plot(12,VSV8_0_1_Bond_Lifetime(1),'s','MarkerSize',26,'LineWidth',4,...
    'MarkerFaceColor','w','MarkerEdgeColor',Color_array(2,:));
plot(12,VSV8_0_1_Bond_Lifetime(3),'d','MarkerSize',26,'LineWidth',4,...
    'MarkerFaceColor',Color_array(2,:),'MarkerEdgeColor',Color_array(2,:));
plot(13,VSV8_0_2_Bond_Lifetime(1),'bs','MarkerSize',26,'LineWidth',4,...
    'MarkerFaceColor','w');
plot(13,VSV8_0_2_Bond_Lifetime(3),'d','MarkerSize',26,'LineWidth',4,...
    'MarkerFaceColor','b','MarkerEdgeColor','b');
plot(14,VSV8_0_3_Bond_Lifetime(1),'s','MarkerSize',26,'LineWidth',4,...
    'MarkerFaceColor','w','MarkerEdgeColor',Color_array(4,:));
plot(14,VSV8_0_3_Bond_Lifetime(3),'d','MarkerSize',26,'LineWidth',4,...
    'MarkerFaceColor',Color_array(4,:),'MarkerEdgeColor',Color_array(4,:));
plot(15,VSV8_1x_Bond_Lifetime(3),'d','MarkerSize',26,'LineWidth',4,...
    'MarkerFaceColor','r','MarkerEdgeColor','r');

h = legend('slip','catch'); 
set(h,'EdgeColor','w','Interpreter','LaTeX','Location','NorthWest','FontSize',65); 
box on; axis([0 16 0 0.80]);hold off;