% Stop_prob_visualization.m

load('Stop_prob_data.mat');
Color_array     = [ 0 1 0; 0 0.749 1; 0 0 1; 0.502 0 1; 1 0 0 ];
XTick_vec_tot   = [ 1 2 3 4 5 7 8 9 10 12 13 14 15 ];
xtick_label_tot = {'$0 \%$','$10 \%$','$20 \%$','$30 \%$','$100 \%$','$10 \%$',...
    '$20 \%$','$30 \%$','$100 \%$','$10 \%$','$20 \%$','$30 \%$','$100 \%$'};

figure(6); hold on; set(gcf,'Color','w'); 
set(gca,'TickLabelInterpreter','LaTeX','XTick',XTick_vec_tot,'XTickLabel',...
    xtick_label_tot,'LineWidth',2.5,'FontSize',60); xtickangle(45); 
ylabel('$\mathrm{P}_{\mathrm{stop}}$','Interpreter','LaTeX','FontSize',90);
% plot(-10,0,'ko','MarkerSize',26,'LineWidth',4,'MarkerFaceColor','w');
% plot(-10,0,'ks','MarkerSize',26,'LineWidth',4,'MarkerFaceColor','w');
% plot(-10,0,'kd','MarkerSize',26,'LineWidth',4,'MarkerFaceColor','w');

% plot(1,PE1_1x_stop_Vthr_0_25(1),'go','MarkerSize',26,'LineWidth',4,...
%     'MarkerFaceColor','w');
plot(1,PE1_1x_stop_Vthr_0_25(2),'gs','MarkerSize',26,'LineWidth',4,...
    'MarkerFaceColor','g');
% plot(1,PE1_1x_stop_Vthr_0_25(3),'gd','MarkerSize',26,'LineWidth',4,...
%     'MarkerFaceColor','w');

% plot(2,PSSB_0_1_stop_Vthr_0_25(1),'o','MarkerSize',26,'LineWidth',4,...
%     'MarkerFaceColor','w','MarkerEdgeColor',Color_array(2,:));
plot(2,PSSB_0_1_stop_Vthr_0_25(2),'s','MarkerSize',26,'LineWidth',4,...
    'MarkerFaceColor',Color_array(2,:),'MarkerEdgeColor',Color_array(2,:));
% plot(2,PSSB_0_1_stop_Vthr_0_25(3),'d','MarkerSize',26,'LineWidth',4,...
%     'MarkerFaceColor','w','MarkerEdgeColor',Color_array(2,:));

% plot(3,PSSB_0_2_stop_Vthr_0_25(1),'bo','MarkerSize',26,'LineWidth',4,...
%     'MarkerFaceColor','w');
plot(3,PSSB_0_2_stop_Vthr_0_25(2),'bs','MarkerSize',26,'LineWidth',4,...
    'MarkerFaceColor','b');
% plot(3,PSSB_0_2_stop_Vthr_0_25(3),'bd','MarkerSize',26,'LineWidth',4,...
%     'MarkerFaceColor','w');

% plot(4,PSSB_0_3_stop_Vthr_0_25(1),'o','MarkerSize',26,'LineWidth',4,...
%     'MarkerFaceColor','w','MarkerEdgeColor',Color_array(4,:));
plot(4,PSSB_0_3_stop_Vthr_0_25(2),'s','MarkerSize',26,'LineWidth',4,...
    'MarkerFaceColor',Color_array(4,:),'MarkerEdgeColor',Color_array(4,:));
% plot(4,PSSB_0_3_stop_Vthr_0_25(3),'d','MarkerSize',26,'LineWidth',4,...
%     'MarkerFaceColor','w','MarkerEdgeColor',Color_array(4,:));

% plot(5,PSSB_1x_stop_Vthr_0_25(1),'ro','MarkerSize',26,'LineWidth',4,...
%     'MarkerFaceColor','w');
plot(5,PSSB_1x_stop_Vthr_0_25(2),'rs','MarkerSize',26,'LineWidth',4,...
    'MarkerFaceColor','r');
% plot(5,PSSB_1x_stop_Vthr_0_25(3),'rd','MarkerSize',26,'LineWidth',4,...
%     'MarkerFaceColor','w');

% plot(7,POVA_0_1_stop_Vthr_0_25(1),'o','MarkerSize',26,'LineWidth',4,...
%     'MarkerFaceColor','w','MarkerEdgeColor',Color_array(2,:));
plot(7,POVA_0_1_stop_Vthr_0_25(2),'s','MarkerSize',26,'LineWidth',4,...
    'MarkerFaceColor','w','MarkerEdgeColor',Color_array(2,:));
% plot(7,POVA_0_1_stop_Vthr_0_25(3),'d','MarkerSize',26,'LineWidth',4,...
%     'MarkerFaceColor','w','MarkerEdgeColor',Color_array(2,:));

% plot(8,POVA_0_2_stop_Vthr_0_25(1),'bo','MarkerSize',26,'LineWidth',4,...
%     'MarkerFaceColor','w');
plot(8,POVA_0_2_stop_Vthr_0_25(2),'bs','MarkerSize',26,'LineWidth',4,...
    'MarkerFaceColor','w');
% plot(8,POVA_0_2_stop_Vthr_0_25(3),'bd','MarkerSize',26,'LineWidth',4,...
%     'MarkerFaceColor','w');

% plot(9,POVA_0_3_stop_Vthr_0_25(1),'o','MarkerSize',26,'LineWidth',4,...
%     'MarkerFaceColor','w','MarkerEdgeColor',Color_array(4,:));
plot(9,POVA_0_3_stop_Vthr_0_25(2),'s','MarkerSize',26,'LineWidth',4,...
    'MarkerFaceColor','w','MarkerEdgeColor',Color_array(4,:));
% plot(9,POVA_0_3_stop_Vthr_0_25(3),'d','MarkerSize',26,'LineWidth',4,...
%     'MarkerFaceColor','w','MarkerEdgeColor',Color_array(4,:));

% plot(10,POVA_1x_stop_Vthr_0_25(1),'ro','MarkerSize',26,'LineWidth',4,...
%     'MarkerFaceColor','w');
plot(10,POVA_1x_stop_Vthr_0_25(2),'rs','MarkerSize',26,'LineWidth',4,...
    'MarkerFaceColor','w');
% plot(10,POVA_1x_stop_Vthr_0_25(3),'rd','MarkerSize',26,'LineWidth',4,...
%     'MarkerFaceColor','w');

% plot(12,PVSV8_0_1_stop_Vthr_0_25(1),'o','MarkerSize',26,'LineWidth',4,...
%     'MarkerFaceColor','w','MarkerEdgeColor',Color_array(2,:));
plot(12,PVSV8_0_1_stop_Vthr_0_25(2),'s','MarkerSize',26,'LineWidth',4,...
    'MarkerFaceColor',Color_array(2,:),'MarkerEdgeColor',Color_array(2,:));
% plot(12,PVSV8_0_1_stop_Vthr_0_25(3),'d','MarkerSize',26,'LineWidth',4,...
%     'MarkerFaceColor','w','MarkerEdgeColor',Color_array(2,:));

% plot(13,PVSV8_0_2_stop_Vthr_0_25(1),'bo','MarkerSize',26,'LineWidth',4,...
%     'MarkerFaceColor','w');
plot(13,PVSV8_0_2_stop_Vthr_0_25(2),'bs','MarkerSize',26,'LineWidth',4,...
    'MarkerFaceColor','b');
% plot(13,PVSV8_0_2_stop_Vthr_0_25(3),'bd','MarkerSize',26,'LineWidth',4,...
%     'MarkerFaceColor','w');

% plot(14,PVSV8_0_3_stop_Vthr_0_25(1),'o','MarkerSize',26,'LineWidth',4,...
%     'MarkerFaceColor','w','MarkerEdgeColor',Color_array(4,:));
plot(14,PVSV8_0_3_stop_Vthr_0_25(2),'s','MarkerSize',26,'LineWidth',4,...
    'MarkerFaceColor',Color_array(4,:),'MarkerEdgeColor',Color_array(4,:));
% plot(14,PVSV8_0_3_stop_Vthr_0_25(3),'d','MarkerSize',26,'LineWidth',4,...
%     'MarkerFaceColor','w','MarkerEdgeColor',Color_array(4,:));

% plot(15,PVSV8_1x_stop_Vthr_0_25(1),'ro','MarkerSize',26,'LineWidth',4,...
%     'MarkerFaceColor','w');
plot(15,PVSV8_1x_stop_Vthr_0_25(2),'rs','MarkerSize',26,'LineWidth',4,...
    'MarkerFaceColor','r');
% plot(15,PVSV8_1x_stop_Vthr_0_25(3),'rd','MarkerSize',26,'LineWidth',4,...
%     'MarkerFaceColor','w');

% h = legend('$t_{\mathrm{window}}$ $=$ $5$ $\mathrm{s}$',...
%     '$t_{\mathrm{window}}$ $=$ $10$ $\mathrm{s}$',...
%     '$t_{\mathrm{window}}$ $=$ $15$ $\mathrm{s}$'); 
% set(h,'EdgeColor','w','Interpreter','LaTeX','Location','NorthWest','FontSize',65); 
box on; axis([0 16 0 1.05]); hold off;